### ISSUE TITLE
Presign URL download is broken

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#440] opened 2024-06-07 10:37 UTC
A few days ago, it worked fine, but now when I try to download an asset using the "Download" button, I get this:
![image](https://github.com/radiantearth/stac-browser/assets/866124/aac6a836-388b-42bd-a0cf-2c267fc8ac32)

The asset URL looks like this:
```
https://.../20240607_051027_739120_MS_NS31_l1d_0_2_0_SATL-4KM-53N_464_3756_preview.png?x-user=no-user-in-request&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...
```

and it works perfectly when used directly.

I use https://radiantearth.github.io/stac-browser

**Comment by m-mohr** [comment] 2024-06-08 00:18
Likely due to https://github.com/radiantearth/stac-browser/pull/429

Please provide a reproducible example, otherwise I can't fix it.

**Comment by drnextgis** [comment] 2024-06-08 08:32
I've made this dummy example: https://radiantearth.github.io/stac-browser/#/external/run.mocky.io/v3/5f503055-07af-4750-8578-20cc3a727331

 @m-mohr, is this example suitable to proceed with?

**Comment by m-mohr** [comment] 2024-06-08 08:53
@drnextgis Thanks. If I click download in your example it downloads without issues for me (Windows, Firefox, ...)
I'm really not sure what you are seeing there,  I've never seen that before I think, but the screenshot also is not capturing the while screen it seems.
Can you give some more infos on OS, Browser, versions, etc.? Does it work for you in other browsers or without plugins?

**Comment by drnextgis** [comment] 2024-06-08 10:17
I see that there are at least two issues:

1. The asset should be downloaded with name `645.tif` because `Content-Disposition` header is set:
```
$ http -v https://rykovd.nextgis.com/api/resource/645/download\?x-user\=no-user-in-request\&X-Amz-Algorithm\=AWS4-HMAC-SHA256
GET /api/resource/645/download?x-user=no-user-in-request&X-Amz-Algorithm=AWS4-HMAC-SHA256 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: rykovd.nextgis.com
User-Agent: HTTPie/2.6.0



HTTP/1.1 200 OK
Connection: keep-alive
Content-Disposition: attachment; filename=645.tif
Content-Length: 3245330
Content-Type: image/tiff; application=geotiff
Date: Sat, 08 Jun 2024 10:12:15 GMT
Last-Modified: Sat, 08 Jun 2024 08:27:41 GMT
Server: openresty/1.25.3.1
```

2. STAC Browser interprets GET parameters as a file name

OS: Ubuntu 22.04.4 LTS
Browser: Google Chrome Version 125.0.6422.141

**Comment by m-mohr** [comment] 2024-06-09 21:36
Thanks, should be fixed.

**Closed by m-mohr** 2024-06-09 21:36 UTC
Labels: needs reprex

**Comment by drnextgis** [comment] 2024-06-09 21:41
Thank you for resolving this issue @m-mohr. I can confirm that it is now fixed.

P.S. I apologize you had to work over the weekend.
