### ISSUE TITLE
Showing asset thumbnails for Collections

### ISSUE THREAD

**Issue by schwehr** [radiantearth/stac-browser#75] opened 2021-04-27 15:56 UTC
Feature Request: Thumbnail previews would be really nice to show for STAC Collections.  

I tried this:

```json
   "assets": {
      "thumbnail": {
         "href": "https://mw1.google.com/ges/dd/images/AAFC_ACI_sample.png",
         "title": "Thumbnail",
         "type": "image/png",
         "roles": ["thumbnail"]
      }
   },
```

Here: https://storage.googleapis.com/earthengine-stac-experimental/catalog-v016/AAFC_ACI_2.json

That adds an `Assets` tab with a `Thumbnail` row:

![Screen Shot 2021-04-27 AAFC/ACI with Thumbnail](https://user-images.githubusercontent.com/389869/116273120-54571d80-a736-11eb-81f8-f66beb7c091a.png)

https://gitter.im/SpatioTemporal-Asset-Catalog/1.0-testing?at=6087a613da3e853b33d64b2d

**Comment by m-mohr** [comment] 2021-04-27 16:21
Yes, I'll take this on and implement in the next weeks. Should be simple to derive (aka copy&paste) from the Items.

**Comment by m-mohr** [comment] 2021-05-09 17:22
Just realized that this is a duplicate of #52

**Closed by m-mohr** 2021-05-09 17:22 UTC
