### ISSUE TITLE
Enhanced COG Viewer Visualization for Multiband COGTIF Images

### ISSUE THREAD

**Issue by davidoesch** [radiantearth/stac-browser#404] opened 2024-01-30 16:04 UTC
### Description:
Currently, the COG Viewer instac_browser displays only the 3-band RGB data of COGTIF images as Iundestand it. I propose an enhancement to the viewer to handle multiband COGTIF images intelligently by stretching and displaying the first three bands. Might linked to https://github.com/radiantearth/stac-browser/issues/385

### Use Case:
As demonstrated by the following example file:
[Example COGTIF File](https://d29cp2gnktw6by.cloudfront.net/data/S2_LEVEL_2A/20240111T102401/S2_L2A_SR_20240111T102401_20240111T102415_10M_run20240112.tif) all 10m bands of Sentinel 2 as COG tiff

Expected results
When visualizing this file, the frist three bands are histogram stretched in RGB, as  in the COG Viewer ([COG Viewer Link] (https://www.cogeo.org/map/#/url/https%3A%2F%2Fd29cp2gnktw6by.cloudfront.net%2Fdata%2FS2_LEVEL_2A%2F20240111T102401%2FS2_L2A_SR_20240111T102401_20240111T102415_10M_run20240112.tif/center/8.8456,46.6886/zoom/11)),
example
![image](https://github.com/radiantearth/stac-browser/assets/4577727/27e342ef-0048-48c3-bd19-ad4d42f51fb2)

Current result in stac Browser:
the current behavior AFAIK displays RGB first three Bands, but not stretched .
![image](https://github.com/radiantearth/stac-browser/assets/4577727/c5e1055b-3658-46db-935f-3c7ff3e7879e)

### Proposed Enhancement:
1. **Utilize Multiband Data:** The COG Viewer should intelligently utilize multiband data by stretching and displaying the first three bands.

2. **Enhanced Visualization:** This enhancement would provide a more informative and visually rich representation of the image, especially in cases where additional spectral information is available beyond RGB.

#### Improved Data Interpretation:
- Multiband data often contains valuable information beyond RGB, enabling users to make more informed decisions. So users can quickly see if scene contains cloud or not

#### Enhanced User Experience:
- Users benefit from a more versatile and feature-rich COG Viewer that can handle a broader range of remote sensing data.

#### No need for thumbnail:
- Wor aroudn so far is to generate a low res RGB Thumbnail ....

### Additional Consideration:
It might be beneficial to include user-configurable options for band selection or custom band combinations for advanced users who wish to tailor their visualization.

### Conclusion:
Implementing this feature will not only align the COG Viewer with viewing capabilities but also enhance the user experience by providing more comprehensive insights into the displayed imagery.

cc @p1d1d1 @Tschoun

**Comment by m-mohr** [comment] 2024-02-06 10:49
Yes, fully agreed. We have two very similar issues:
- https://github.com/radiantearth/stac-browser/issues/309
- https://github.com/radiantearth/stac-browser/issues/12
This is the place where it actually needs to be implemented:
- https://github.com/stac-utils/stac-layer/issues/62

STAC Browser currently uses stac-layer 0.15. I'm not sure right now whether this would get better with stac-layer 1.0.
There's also still the discussion to migrate to ol-stac. Both stac-layer 1.0 und ol-stac would support enhancing the visualization through metadata though (e.g. statistics).

I'll close this as duplicate of #12, but you wrote a good text so I'd love to see you repost this in #12.
Generally, there's funding or an external contribution needed to improve this.

**Closed by m-mohr** 2024-02-06 10:49 UTC
